### ISSUE TITLE
Trouble installing package

### ISSUE THREAD

**Issue by sshaikh08** [SaltieRL/carball#142]
I'm trying to install carball to an anaconda environment using the instructions in the readme. I keep getting this error:

ERROR: Could not find a version that satisfies the requirement python (from versions: none)
ERROR: No matching distribution found for python

I'm using python 3.7,
can anybody help me?

**Comment by dtracers** [comment]
it is not a conda package but a pypi one

**Comment by sshaikh08** [comment]
I tried installing using pip, is there another way I'm supposed to install it?

**Comment by Sciguymjm** [comment]
Can you let us know what the exact command you used was?

**Comment by PollieDev** [comment]
Hey, didn't want to re-open since my issue is also related to this issue:

I'm having a problem installing the package. I'm not too familiar with Python. Trying to make a python script that'll transform and analyze a replay into a json file for use in other languages.

I installed Python 3.6.0 on w10 with pip. I used the command: `pip install carball` but I'm receiving this error: `ImportError: DLL load failed: The specified procedure could not be found.`. (I think that's the error).

If you want the full error log, please refer to: https://pastebin.com/8vfsQppv

Thank you so much for this tool and for calculated.gg. Amazing site and amazing processing.
Hoping to be able to use this powerfull tool.

Kind regards,
Pollie

**Comment by twobackfromtheend** [comment]
Hi,

This seems to be an issue with the protobuf library. See https://github.com/protocolbuffers/protobuf/issues/5046. It seems that using python 3.6.1 fixes it.

Thanks for your kind words :)
